/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef NV_CTRL_TABLE_INTERFACE_H
#define NV_CTRL_TABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "nvCtrlTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _nvCtrlTable_initialize_interface(nvCtrlTable_registration * user_ctx,
                                    u_long flags);
void _nvCtrlTable_shutdown_interface(nvCtrlTable_registration * user_ctx);

nvCtrlTable_registration *
nvCtrlTable_registration_get( void );

nvCtrlTable_registration *
nvCtrlTable_registration_set( nvCtrlTable_registration * newreg );

netsnmp_container *nvCtrlTable_container_get( void );
int nvCtrlTable_container_size( void );

    nvCtrlTable_rowreq_ctx * nvCtrlTable_allocate_rowreq_ctx(void);
void nvCtrlTable_release_rowreq_ctx(nvCtrlTable_rowreq_ctx *rowreq_ctx);

int nvCtrlTable_index_to_oid(netsnmp_index *oid_idx,
                            nvCtrlTable_mib_index *mib_idx);
int nvCtrlTable_index_from_oid(netsnmp_index *oid_idx,
                              nvCtrlTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void nvCtrlTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* NV_CTRL_TABLE_INTERFACE_H */
/** @} */
