/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "nvCtrlTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "nvCtrlTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table nvCtrlTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NV-CTRL-MIB::nvCtrlTable is subid 2 of nvCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.2021.13.42.2, length: 10
*/
typedef struct nvCtrlTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache;

   nvCtrlTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

} nvCtrlTable_interface_ctx;

static nvCtrlTable_interface_ctx nvCtrlTable_if_ctx;

static void _nvCtrlTable_container_init(
    nvCtrlTable_interface_ctx *if_ctx);
static void _nvCtrlTable_container_shutdown(
    nvCtrlTable_interface_ctx *if_ctx);


netsnmp_container *
nvCtrlTable_container_get( void )
{
    return nvCtrlTable_if_ctx.container;
}

nvCtrlTable_registration *
nvCtrlTable_registration_get( void )
{
    return nvCtrlTable_if_ctx.user_ctx;
}

nvCtrlTable_registration *
nvCtrlTable_registration_set( nvCtrlTable_registration * newreg )
{
    nvCtrlTable_registration * old = nvCtrlTable_if_ctx.user_ctx;
    nvCtrlTable_if_ctx.user_ctx = newreg;
    return old;
}

int
nvCtrlTable_container_size( void )
{
    return CONTAINER_SIZE(nvCtrlTable_if_ctx.container);
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_nvCtrlTable_pre_request;
static Netsnmp_Node_Handler _mfd_nvCtrlTable_post_request;
static Netsnmp_Node_Handler _mfd_nvCtrlTable_object_lookup;
static Netsnmp_Node_Handler _mfd_nvCtrlTable_get_values;
/**
 * @internal
 * Initialize the table nvCtrlTable 
 *    (Define its contents and how it's structured)
 */
void
_nvCtrlTable_initialize_interface(nvCtrlTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &nvCtrlTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &nvCtrlTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:nvCtrlTable:_nvCtrlTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for nvCtrlTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: nvCtrlGPU */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrival. */
    tbl_info->min_column = NV_CTRL_TABLE_MIN_COL;
    tbl_info->max_column = NV_CTRL_TABLE_MAX_COL;

    /*
     * save users context
     */
    nvCtrlTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    nvCtrlTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _nvCtrlTable_container_init(&nvCtrlTable_if_ctx);
    if (NULL == nvCtrlTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for nvCtrlTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_nvCtrlTable_object_lookup;
    access_multiplexer->get_values = _mfd_nvCtrlTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_nvCtrlTable_pre_request;
    access_multiplexer->post_request = _mfd_nvCtrlTable_post_request;


    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("nvCtrlTable:init_nvCtrlTable",
                "Registering nvCtrlTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("nvCtrlTable", handler,
                                                  nvCtrlTable_oid,
                                                  nvCtrlTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
                                                  HANDLER_CAN_RONLY
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table nvCtrlTable\n");
        return;
    }
    reginfo->my_reg_void = &nvCtrlTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            nvCtrlTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != nvCtrlTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(nvCtrlTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _nvCtrlTable_initialize_interface */

/**
 * @internal
 * Shutdown the table nvCtrlTable
 */
void
_nvCtrlTable_shutdown_interface(nvCtrlTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _nvCtrlTable_container_shutdown(&nvCtrlTable_if_ctx);
}

void
nvCtrlTable_valid_columns_set(netsnmp_column_info *vc)
{
    nvCtrlTable_if_ctx.tbl_info.valid_columns = vc;
} /* nvCtrlTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
nvCtrlTable_index_to_oid(netsnmp_index *oid_idx,
                         nvCtrlTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * nvCtrlGPU(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
     */
    netsnmp_variable_list var_nvCtrlGPU;

    /*
     * set up varbinds
     */
    memset( &var_nvCtrlGPU, 0x00, sizeof(var_nvCtrlGPU) );
    var_nvCtrlGPU.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_nvCtrlGPU.next_variable =  NULL;


    DEBUGMSGTL(("verbose:nvCtrlTable:nvCtrlTable_index_to_oid","called\n"));

        /* nvCtrlGPU(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    snmp_set_var_value(&var_nvCtrlGPU, (u_char*)&mib_idx->nvCtrlGPU,
                       sizeof(mib_idx->nvCtrlGPU));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_nvCtrlGPU);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_nvCtrlGPU );

    return err;
} /* nvCtrlTable_index_to_oid */

/**
 * extract nvCtrlTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
nvCtrlTable_index_from_oid(netsnmp_index *oid_idx,
                         nvCtrlTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * nvCtrlGPU(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
     */
    netsnmp_variable_list var_nvCtrlGPU;

    /*
     * set up varbinds
     */
    memset( &var_nvCtrlGPU, 0x00, sizeof(var_nvCtrlGPU) );
    var_nvCtrlGPU.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_nvCtrlGPU.next_variable =  NULL;


    DEBUGMSGTL(("verbose:nvCtrlTable:nvCtrlTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_nvCtrlGPU );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->nvCtrlGPU = *((long *)var_nvCtrlGPU.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_nvCtrlGPU );

    return err;
} /* nvCtrlTable_index_from_oid */


/* *********************************************************************
 * @internal
 * allocate resources for a nvCtrlTable_rowreq_ctx
 */
nvCtrlTable_rowreq_ctx *
nvCtrlTable_allocate_rowreq_ctx(void)
{
    nvCtrlTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(nvCtrlTable_rowreq_ctx);

    DEBUGMSGTL(("internal:nvCtrlTable:nvCtrlTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "nvCtrlTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->nvCtrlTable_data_list = NULL;


    return rowreq_ctx;
} /* nvCtrlTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a nvCtrlTable_rowreq_ctx
 */
void
nvCtrlTable_release_rowreq_ctx(nvCtrlTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:nvCtrlTable:nvCtrlTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    

    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* nvCtrlTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_nvCtrlTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:nvCtrlTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = nvCtrlTable_pre_request(nvCtrlTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("nvCtrlTable","error %d from "
                    "nvCtrlTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_nvCtrlTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_nvCtrlTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    nvCtrlTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        nvCtrlTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:nvCtrlTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    rc = nvCtrlTable_post_request(nvCtrlTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("nvCtrlTable","error %d from "
                    "nvCtrlTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_nvCtrlTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_nvCtrlTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    nvCtrlTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * nvCtrlTable_interface_ctx *if_ctx =
     *             (nvCtrlTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        nvCtrlTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_nvCtrlTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_nvCtrlTable_get_column( nvCtrlTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* (INDEX) nvCtrlGPU(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU:
    var->type = ASN_INTEGER;
        var->val_len = sizeof(long);
        (*var->val.integer) = rowreq_ctx->tbl_idx.nvCtrlGPU;
        break;

    /* nvCtrlProductName(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_NV_CTRL_PRODUCT_NAME:
        if (! (COLUMN_NV_CTRL_PRODUCT_NAME_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlProductName) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->type = ASN_OCTET_STR;
rc = nvCtrlProductName_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* nvCtrlVBiosVersion(3)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_NV_CTRL_VBIOS_VERSION:
        if (! (COLUMN_NV_CTRL_VBIOS_VERSION_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlVBiosVersion) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->type = ASN_OCTET_STR;
rc = nvCtrlVBiosVersion_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* nvCtrlNvidiaDriverVersion(4)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_NV_CTRL_NVIDIA_DRIVER_VERSION:
        if (! (COLUMN_NV_CTRL_NVIDIA_DRIVER_VERSION_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlNvidiaDriverVersion) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->type = ASN_OCTET_STR;
rc = nvCtrlNvidiaDriverVersion_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* nvCtrlVersion(5)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_NV_CTRL_VERSION:
        if (! (COLUMN_NV_CTRL_VERSION_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlVersion) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->type = ASN_OCTET_STR;
rc = nvCtrlVersion_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* nvCtrlBusType(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_BUS_TYPE:
        if (! (COLUMN_NV_CTRL_BUS_TYPE_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlBusType) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlBusType_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlBusRate(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_BUS_RATE:
        if (! (COLUMN_NV_CTRL_BUS_RATE_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlBusRate) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlBusRate_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlVideoRam(8)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_VIDEO_RAM:
        if (! (COLUMN_NV_CTRL_VIDEO_RAM_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlVideoRam) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlVideoRam_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlIrq(9)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_IRQ:
        if (! (COLUMN_NV_CTRL_IRQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlIrq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlIrq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUCoreTemp(10)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_CORE_TEMP:
        if (! (COLUMN_NV_CTRL_GPU_CORE_TEMP_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUCoreTemp) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUCoreTemp_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUCoreThreshold(11)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_CORE_THRESHOLD:
        if (! (COLUMN_NV_CTRL_GPU_CORE_THRESHOLD_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUCoreThreshold) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUCoreThreshold_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUDefaultCoreThreshold(12)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_DEFAULT_CORE_THRESHOLD:
        if (! (COLUMN_NV_CTRL_GPU_DEFAULT_CORE_THRESHOLD_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUDefaultCoreThreshold) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUDefaultCoreThreshold_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUMaxCoreThreshold(13)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_MAX_CORE_THRESHOLD:
        if (! (COLUMN_NV_CTRL_GPU_MAX_CORE_THRESHOLD_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUMaxCoreThreshold) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUMaxCoreThreshold_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUAmbientTemp(14)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_AMBIENT_TEMP:
        if (! (COLUMN_NV_CTRL_GPU_AMBIENT_TEMP_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUAmbientTemp) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUAmbientTemp_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUOverclockingState(15)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_OVERCLOCKING_STATE:
        if (! (COLUMN_NV_CTRL_GPU_OVERCLOCKING_STATE_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUOverclockingState) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUOverclockingState_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPU2DGPUClockFreq(16)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_2D_GPU_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_2D_GPU_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPU2DGPUClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPU2DGPUClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPU2DMemClockFreq(17)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_2D_MEM_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_2D_MEM_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPU2DMemClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPU2DMemClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPU3DGPUClockFreq(18)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_3D_GPU_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_3D_GPU_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPU3DGPUClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPU3DGPUClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPU3DMemClockFreq(19)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_3D_MEM_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_3D_MEM_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPU3DMemClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPU3DMemClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUDefault2DGPUClockFreq(20)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_DEFAULT_2D_GPU_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_DEFAULT_2D_GPU_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUDefault2DGPUClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUDefault2DGPUClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUDefault2DMemClockFreq(21)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_DEFAULT_2D_MEM_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_DEFAULT_2D_MEM_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUDefault2DMemClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUDefault2DMemClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUDefault3DGPUClockFreq(22)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_DEFAULT_3D_GPU_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_DEFAULT_3D_GPU_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUDefault3DGPUClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUDefault3DGPUClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUDefault3DMemClockFreq(23)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_DEFAULT_3D_MEM_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_DEFAULT_3D_MEM_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUDefault3DMemClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUDefault3DMemClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUCurrentGPUClockFreq(24)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_CURRENT_GPU_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_CURRENT_GPU_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUCurrentGPUClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUCurrentGPUClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* nvCtrlGPUCurrentMemClockFreq(25)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_NV_CTRL_GPU_CURRENT_MEM_CLOCK_FREQ:
        if (! (COLUMN_NV_CTRL_GPU_CURRENT_MEM_CLOCK_FREQ_FLAG & rowreq_ctx->column_exists_flags)) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                        "column %d (nvCtrlGPUCurrentMemClockFreq) doesn't exist\n", column));
            return MFD_SKIP;
        }

    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = nvCtrlGPUCurrentMemClockFreq_get(rowreq_ctx, (long *)var->val.string );
        break;

     default:
        if (NV_CTRL_TABLE_MIN_COL <= column && column <= NV_CTRL_TABLE_MAX_COL) {
            DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _nvCtrlTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _nvCtrlTable_get_column */

int
_mfd_nvCtrlTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    nvCtrlTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:nvCtrlTable:_mfd_nvCtrlTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    DEBUGMSGTL(("9:nvCtrlTable:_mfd_nvCtrlTable_get_values",
                "exists %p\n", (void*)rowreq_ctx->column_exists_flags));

    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _nvCtrlTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_nvCtrlTable_get_values */


/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * SET PROCESSING NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free(netsnmp_container *container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:nvCtrlTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for nvCtrlTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return nvCtrlTable_container_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:nvCtrlTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in nvCtrlTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    _container_free(container);
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(nvCtrlTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:nvCtrlTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    nvCtrlTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:nvCtrlTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in nvCtrlTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    nvCtrlTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_nvCtrlTable_container_init(nvCtrlTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:nvCtrlTable:_nvCtrlTable_container_init","called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         nvCtrlTable_oid,
                                         nvCtrlTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for nvCtrlTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    nvCtrlTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("nvCtrlTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "nvCtrlTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void*)if_ctx->container;
} /* _nvCtrlTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_nvCtrlTable_container_shutdown(nvCtrlTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:nvCtrlTable:_nvCtrlTable_container_shutdown","called\n"));

    nvCtrlTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _nvCtrlTable_container_shutdown */


nvCtrlTable_rowreq_ctx *
nvCtrlTable_row_find_by_mib_index(nvCtrlTable_mib_index *mib_idx)
{
    nvCtrlTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = nvCtrlTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = CONTAINER_FIND(nvCtrlTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

